version: '3.7'

services:
  bemember-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/node/app/src
    container_name: bemember-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn dev
